version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  spiderman:
    image: ${DOCKER_REGISTRY-}spiderman
    container_name: spiderman
    build:
      context: .
      dockerfile: Spiderman/Dockerfile

  batman:
    image: ${DOCKER_REGISTRY-}batman
    container_name: batman
    build:
      context: .
      dockerfile: Batman/Dockerfile
  
